# Generated by Django 5.2.17 on 2026-10-01 18:54

import apps.tenants.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(help_text='Usado na página pública: app.com/<slug>', max_length=60, unique=True, validators=[apps.tenants.models.validate_slug_not_reserved], verbose_name='endereço (slug)')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64, verbose_name='fuso horário')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('settings_json', models.JSONField(blank=True, default=dict, verbose_name='configurações')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('SUSPENDED', 'Suspenso')], default='ACTIVE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'estabelecimento',
                'verbose_name_plural': 'estabelecimentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('ATTENDANT', 'Atendente'), ('PROVIDER', 'Prestador'), ('CLIENT', 'Cliente')], max_length=12)),
                ('status', models.CharField(choices=[('INVITED', 'Convidado'), ('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenants.establishment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vínculo',
                'verbose_name_plural': 'vínculos',
                'indexes': [models.Index(fields=['establishment', 'role', 'status'], name='tenants_mem_establi_53b6e6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'establishment', 'role'), name='uniq_membership_user_establishment_role')],
            },
        ),
    ]
